"""Continuous motion (CMD=2) — letter_spinningcam_velocity_path.md.

The promises being pinned here, in the order they matter:

1. OFF is byte-identical: no CMD=2 anywhere, nothing else moves. A production
   PLC skips CMD=2, so a stray one is a machine that jumps between points.
2. With it on, no line is added or removed and feeds are only ever LOWERED —
   the toolpath and the line budget are untouched.
3. The corner rules are the letter's: exact stop (CMD=1) at corners of at
   least the stop angle, F = tol / (T * sin theta) rounded DOWN below it.
4. A cutting move with F = 0 refuses the export (the PLC would refuse the
   recipe at pre-scan).
5. The file still passes its own geometry + checksum validation, and says in
   its header that it is for the experimental PLC only.

Run:  python _test_continuous_motion.py
"""
import math
import re
import sys

from recipe_to_scl import (
    GCodeToSCLConverter, continuous_settings, plan_continuous_motion,
    check_scl_geometry, recipe_checksum, CONTINUOUS_DEFAULTS,
    CMD_LINEAR, CMD_LINEAR_CONTINUOUS,
)

FAILED = []


def check(name, cond, detail=""):
    if cond:
        print(f"  ok   {name}")
    else:
        print(f"  FAIL {name}" + (f"  -- {detail}" if detail else ""))
        FAILED.append(name)


def cfg(**over):
    p = {"plc_mode": True, "plc_continuous": True}
    p.update(over)
    return continuous_settings(p)


def convert(gcode, cont=None, markers=False):
    c = GCodeToSCLConverter(emit_pass_markers=markers, continuous_motion=cont)
    c.parse_gcode(gcode)
    return c


def g1s(c):
    return [l for l in c.lines if l.cmd in (CMD_LINEAR, CMD_LINEAR_CONTINUOUS)]


def rows(c):
    return [(l.cmd, l.param, l.f, round(l.x, 3), round(l.z, 3)) for l in c.lines]


TURRET = {"turret_slots": [{"code": 4, "angle": 0.0}]}

# Shaped like a real pass: setup lines, a rapid in, a curve, a retract.
PROGRAM = """\
(--- OPERASYONLAR ---)
(Op1: ROUGHING, 2 paso, T004, R=44.56mm, RPM=600.0, mm_min=300.0)
(--- OP 1 START: ROUGHING ---)
M40 P1
M6 T004 (ROUGHING)
G97 S600 M3
(--- OP 1: ROUGHING - PASO 1 ---)
G0 X100.000 Z10.000
G1 X99.000 Z12.000 F300 (Op1 P1)
G1 X97.500 Z14.000 (Op1 P1)
G1 X95.500 Z15.500 (Op1 P1)
G1 X80.000 Z20.000 (Op1 P1)
G0 X130.000 Z20.000 (Retract Op1 P1)
(--- OP 1: ROUGHING - PASO 2 ---)
G0 X100.000 Z14.000
G1 X99.000 Z16.000 F300 (Op1 P2)
G1 X90.000 Z16.000 (Op1 P2)
G0 X130.000 Z16.000 (Retract Op1 P2)
M30
"""

# --- 1. settings ------------------------------------------------------------
print("settings")
check("off when plc_continuous is off",
      continuous_settings({"plc_mode": True, "plc_continuous": False}) is None)
check("off when PLC mode is off (CMD=2 is recipe-only)",
      continuous_settings({"plc_mode": False, "plc_continuous": True}) is None)
check("off for an empty/None params", continuous_settings(None) is None)
d = cfg()
check("defaults are the letter's numbers",
      (d["scan_time_s"], d["corner_tol_mm"], d["feed_min"], d["reversal_deg"],
       d["stop_slowdown"]) == (0.1, 0.1, 30, 90.0, False), repr(d))
bad = cfg(plc_scan_time_s=0, plc_corner_tol_mm=-1, plc_feed_min="abc",
          plc_reversal_deg=float("nan"))
check("zero / negative / unreadable / NaN fall back to defaults",
      (bad["scan_time_s"], bad["corner_tol_mm"], bad["feed_min"], bad["reversal_deg"])
      == (0.1, 0.1, 30, 90.0), repr(bad))
check("stop angle is capped at 180", cfg(plc_reversal_deg=400)["reversal_deg"] == 180.0)
check("feed_min is a whole number, at least 1", cfg(plc_feed_min=0.4)["feed_min"] == 1)

# --- 2. OFF changes nothing -------------------------------------------------
print("off")
legacy = GCodeToSCLConverter()
legacy.parse_gcode(PROGRAM)
off = convert(PROGRAM, None)
check("no CMD=2 when off", not any(l.cmd == CMD_LINEAR_CONTINUOUS for l in off.lines))
check("off lines == a converter built without the argument", rows(off) == rows(legacy))
strip = lambda s: "\n".join(l for l in s.split("\n") if not l.startswith("// Generated by"))
check("off SCL == a converter built without the argument",
      strip(off.generate_scl("DB_RecipeProgram1", "T", params=TURRET, chunk_size=100))
      == strip(legacy.generate_scl("DB_RecipeProgram1", "T", params=TURRET, chunk_size=100)))
check("off SCL has no continuous-motion header",
      "CONTINUOUS MOTION" not in off.generate_scl("DB_RecipeProgram1", "T", params=TURRET))
check("an empty dict counts as off", convert(PROGRAM, {}).continuous_stats is None)

# --- 3. ON: same lines, same places, feeds only lowered ---------------------
print("on")
on = convert(PROGRAM, cfg())
check("no line added or removed", len(on.lines) == len(off.lines))
check("X/Z/Param and the non-G1 lines are untouched",
      all((a.x, a.z, a.param) == (b.x, b.z, b.param) for a, b in zip(on.lines, off.lines))
      and all(a.cmd == b.cmd for a, b in zip(on.lines, off.lines)
              if b.cmd != CMD_LINEAR))
check("every feed is <= the programmed feed",
      all(a.f <= b.f for a, b in zip(on.lines, off.lines)))
check("cutting lines became CMD=2",
      sum(1 for l in on.lines if l.cmd == CMD_LINEAR_CONTINUOUS) >= 5,
      [l.cmd for l in g1s(on)])
check("rapids stay CMD=0", sum(l.cmd == 0 for l in on.lines) == sum(l.cmd == 0 for l in off.lines))

# --- 4. corner rules ----------------------------------------------------------
print("corners")


def corner(second_x, second_z, **over):
    """G0 to 0,0; G1 to 10,0 at F300; G1 to (second); rapid out."""
    c = convert(f"G0 X0 Z0\nG1 X10 Z0 F300\nG1 X{second_x} Z{second_z}\nG0 X50 Z50\n",
                cfg(**over))
    return g1s(c), c.continuous_stats


g, st = corner(20, 10)          # exactly 45 degrees
check("45 deg corner: arriving line slowed to floor(6/(0.1*sin45)) = 84",
      (g[0].cmd, g[0].f) == (CMD_LINEAR_CONTINUOUS, 84), (g[0].cmd, g[0].f))
# Changed 2026-09-16 (user decision): the line LEAVING a blended corner is planned
# too. After a turn the axes keep drifting along the old heading while they run the
# NEW line, so its speed is what the corner tolerance has to cover. Before this,
# 8-21 corners per real shop program left the corner faster than their own limit.
check("45 deg corner: the leaving line is planned to the same 84",
      (g[1].cmd, g[1].f) == (CMD_LINEAR_CONTINUOUS, 84), (g[1].cmd, g[1].f))
check("45 deg corner counted as slowed", st["slowed_corners"] == 1, st)
check("the leaving line is counted separately", st["slowed_exits"] == 1, st)

g, st = corner(10, 10)          # exactly 90 degrees
check("90 deg corner: arriving line is an exact stop (CMD=1)", g[0].cmd == CMD_LINEAR, g[0].cmd)
check("90 deg corner: feed not planned (the stop does the work)", g[0].f == 300, g[0].f)
check("90 deg corner counted as exact", st["exact_corners"] == 1, st)
check("90 deg corner: the line leaving an EXACT STOP keeps full feed "
      "(it starts from standstill, so there is nothing to drift)",
      (g[1].cmd, g[1].f) == (CMD_LINEAR_CONTINUOUS, 300), (g[1].cmd, g[1].f))
check("...and nothing is counted as a slowed exit", st["slowed_exits"] == 0, st)

g, st = corner(0, 0.001)        # straight back: 180 degrees
check("reversal stops exactly", g[0].cmd == CMD_LINEAR)

g, st = corner(20, 0.349)       # ~2 degrees
check("2 deg corner at F300 keeps full feed", (g[0].cmd, g[0].f) == (CMD_LINEAR_CONTINUOUS, 300))

g, st = corner(20, 10, plc_reversal_deg=10)
check("stop angle 10: a 45 deg corner stops exactly instead of slowing",
      (g[0].cmd, g[0].f) == (CMD_LINEAR, 300), (g[0].cmd, g[0].f))

g, st = corner(20, 10, plc_corner_tol_mm=0.001)
check("tiny tolerance: feed never planned below F min (30)", g[0].f == 30, g[0].f)

c = convert("G0 X0 Z0\nG1 X10 Z0 F20\nG1 X20 Z10\nG0 X50 Z50\n", cfg())
check("a programmed feed below F min is left as programmed", g1s(c)[0].f == 20, g1s(c)[0].f)

g, st = corner(20, 10, plc_scan_time_s=0.2)
check("T is really used: T=0.2 halves the corner feed (84 -> 42)", g[0].f == 42, g[0].f)

c = convert("G0 X0 Z0\nG1 X10 Z0 F300\nG1 X10 Z0\nG1 X20 Z10\nG0 X50 Z50\n", cfg())
check("a zero-length line is looked through, not treated as a straight join",
      g1s(c)[1].f == 84 or g1s(c)[0].f == 84, [l.f for l in g1s(c)])

# Diameter mode: recipe X is a diameter; the angle is measured on the radius.
# Real geometry (0,0)->(10,10)->(10,20) turns 45 deg; the raw diameter numbers
# (0,0)->(20,10)->(20,20) would read as 63.4 deg.
dia = "G0 X0 Z0\nG1 X20 Z10 F300\nG1 X20 Z20\nG0 X50 Z50\n"
check("diameter mode measures the corner on the radius (45 deg -> 84)",
      g1s(convert(dia, cfg(machine_output_diameter_mode=True)))[0].f == 84,
      g1s(convert(dia, cfg(machine_output_diameter_mode=True)))[0].f)
check("radius mode reads the same numbers as 63.4 deg (-> 67)",
      g1s(convert(dia, cfg()))[0].f == 67, g1s(convert(dia, cfg()))[0].f)

# --- 5. exact points ---------------------------------------------------------
print("exact points")
c = convert("G0 X0 Z0\nG1 X5 Z5 F200 (Point Op3)\nG1 X10 Z5 F300\nG0 X50 Z50\n", cfg())
check("a Point op move stays CMD=1", g1s(c)[0].cmd == CMD_LINEAR)
check("the move after it is still CMD=2", g1s(c)[1].cmd == CMD_LINEAR_CONTINUOUS)

# --- 6. feed 0 refuses ------------------------------------------------------
print("zero feed")
try:
    convert("G0 X0 Z0\nG1 X10 Z0 F0\nG0 X50 Z50\n", cfg())
    check("F=0 on a cutting move raises CONT_ZERO_FEED", False, "no error")
except ValueError as e:
    check("F=0 on a cutting move raises CONT_ZERO_FEED", str(e).startswith("CONT_ZERO_FEED:"), str(e))
try:
    convert("G0 X0 Z0\nG1 X10 Z0 F0\nG0 X50 Z50\n", None)
    check("the same program still converts with the option OFF", True)
except ValueError as e:
    check("the same program still converts with the option OFF", False, str(e))

# --- 7. slow down before stops -----------------------------------------------
print("stop slow-down")
run = "G0 X0 Z0\nG1 X10 Z0 F300\nG1 X20 Z0\nG1 X30 Z0\nG0 X30 Z50\n"
check("off by default: a straight run keeps F300",
      [l.f for l in g1s(convert(run, cfg()))] == [300, 300, 300])
c = convert(run, cfg(plc_stop_slowdown=True))
check("on: last line tol/T = 60, the line before 120",
      [l.f for l in g1s(c)] == [300, 120, 60], [l.f for l in g1s(c)])
check("on: counted once", c.continuous_stats["slowed_stops"] == 1, c.continuous_stats)
lone = convert("G0 X0 Z0\nG1 X10 Z0 F300\nG0 X10 Z50\n", cfg(plc_stop_slowdown=True))
check("a lone move is not slowed (a one-line bend keeps its feed)", g1s(lone)[0].f == 300)
# The letter's item-6 picture: slow into the corner, exact stop, new run after.
c = convert("G0 X0 Z0\nG1 X10 Z0 F300\nG1 X20 Z0\nG1 X20 Z10\nG1 X20 Z20\nG0 X50 Z50\n",
            cfg(plc_stop_slowdown=True))
check("letter item 6+7: 120 (CMD=2) -> 60 (CMD=1) at the corner",
      [(l.cmd, l.f) for l in g1s(c)[:2]] == [(2, 120), (1, 60)],
      [(l.cmd, l.f) for l in g1s(c)])

# --- 8. the file ------------------------------------------------------------
print("file")
scl = on.generate_scl("DB_RecipeProgram1", "T", params=TURRET, chunk_size=100)
rep = check_scl_geometry(scl)
check("geometry + checksum self-check passes", rep["ok"], rep["errors"])
check("checksum covers the CMD=2 lines",
      rep["checksum"] == recipe_checksum(on.lines, len(on.lines))
      and rep["checksum"] != recipe_checksum(off.lines, len(off.lines)))
check("header carries the experimental-PLC warning",
      "CONTINUOUS MOTION (CMD=2) - EXPERIMENTAL PLC ONLY" in scl)
check("header states the settings used", "T=0.1 s, corner tol=0.1 mm, F min=30" in scl)
check("no '// CHUNKS:'-like text in the new header lines",
      not any(re.match(r"^//\s*CHUNKS:", l) for l in scl.split("\n")
              if "CMD=2" in l or "EXPERIMENTAL" in l))
check("CMD=2 lines are commented 'G1 Continuous'", "CMD := 2; " in scl and "G1 Continuous" in scl)
with_markers = convert(PROGRAM, cfg(), markers=True)
check("markers + continuous: markers untouched, still no line added",
      len(with_markers.lines) == len(convert(PROGRAM, None, markers=True).lines))

# --- 9. wiring -------------------------------------------------------------
print("wiring")
from machine_loader import MACHINE_PROFILE_KEYS
from i18n import STRINGS
keys = ["plc_continuous", "plc_scan_time_s", "plc_corner_tol_mm",
        "plc_feed_min", "plc_reversal_deg", "plc_stop_slowdown"]
check("all six settings live on the machine profile (a .ssp cannot change them)",
      all(k in MACHINE_PROFILE_KEYS for k in keys),
      [k for k in keys if k not in MACHINE_PROFILE_KEYS])
with open("main.py", encoding="utf-8") as f:
    main_src = f.read()
defaults_ok = True
for k, name in [("plc_scan_time_s", "scan_time_s"), ("plc_corner_tol_mm", "corner_tol_mm"),
                ("plc_feed_min", "feed_min"), ("plc_reversal_deg", "reversal_deg"),
                ("plc_stop_slowdown", "stop_slowdown")]:
    m = re.search(r'"%s":\s*([\w.]+)' % k, main_src)
    if not m:
        defaults_ok = False
        continue
    val = {"True": True, "False": False}.get(m.group(1), None)
    if val is None:
        val = float(m.group(1))
    if val != CONTINUOUS_DEFAULTS[name]:
        defaults_ok = False
check("main.py defaults == CONTINUOUS_DEFAULTS", defaults_ok)
check("main.py default for plc_continuous is False",
      re.search(r'"plc_continuous":\s*False', main_src) is not None)
i18n_keys = ["cb_plc_continuous", "tip_plc_continuous", "lbl_plc_scan_time", "tip_plc_scan_time",
             "lbl_plc_corner_tol", "tip_plc_corner_tol", "lbl_plc_feed_min", "tip_plc_feed_min",
             "lbl_plc_reversal", "tip_plc_reversal", "cb_plc_stop_slowdown",
             "tip_plc_stop_slowdown", "msg_scl_continuous_line", "msg_continuous_zero_feed"]
check("every new string has EN, TR and ES",
      all(k in STRINGS and all(STRINGS[k].get(lang) for lang in ("EN", "TR", "ES"))
          for k in i18n_keys),
      [k for k in i18n_keys if k not in STRINGS])
check("export message formats in all three languages",
      all(STRINGS["msg_scl_continuous_line"][lang].format(n=1, exact=2, slowed=3, exits=5, stops=4)
          and STRINGS["msg_continuous_zero_feed"][lang].format(line=7)
          for lang in ("EN", "TR", "ES")))

print()
if FAILED:
    print(f"FAILED {len(FAILED)}: {FAILED}")
    sys.exit(1)
print("ALL OK")
